services:
  db:
    image: postgres:15
    container_name: biblioteca_db
    env_file: .env  
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
      - ./db/reports_vw.sql:/docker-entrypoint-initdb.d/3-reports_vw.sql
      - ./db/indexes.sql:/docker-entrypoint-initdb.d/4-indexes.sql
      - ./db/roles.sql:/docker-entrypoint-initdb.d/5-roles.sql